2024-07-02 14:40:11,875 INFO: Fetched 15 posts [in C:\Users\15097\Desktop\FinalBlog\app.py:101]
2024-07-02 14:49:34,697 INFO: Blog startup [in C:\Users\15097\Desktop\FinalBlog\app.py:67]
2024-07-02 14:49:37,880 ERROR: Exception on /post/16 [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 201, in view_post
    sanitized_content = sanitize_and_render_markdown(post.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\utils.py", line 123, in sanitize_and_render_markdown
    html_content = markdown(
                   ^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'markdown.markdown(...)'?
2024-07-02 14:49:59,905 INFO: Post created: urls [in C:\Users\15097\Desktop\FinalBlog\app.py:161]
2024-07-02 14:49:59,912 INFO: Fetched 16 posts [in C:\Users\15097\Desktop\FinalBlog\app.py:101]
2024-07-02 14:50:01,458 ERROR: Exception on /post/17 [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 201, in view_post
    sanitized_content = sanitize_and_render_markdown(post.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\utils.py", line 123, in sanitize_and_render_markdown
    html_content = markdown(
                   ^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'markdown.markdown(...)'?
2024-07-02 14:50:52,843 ERROR: Exception on /post/17 [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 201, in view_post
    sanitized_content = sanitize_and_render_markdown(post.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\utils.py", line 123, in sanitize_and_render_markdown
    html_content = markdown(
                   ^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'markdown.markdown(...)'?
2024-07-02 14:52:46,396 INFO: Blog startup [in C:\Users\15097\Desktop\FinalBlog\app.py:67]
2024-07-02 14:52:53,404 ERROR: Exception on /post/17 [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 201, in view_post
    sanitized_content = sanitize_and_render_markdown(post.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\utils.py", line 124, in sanitize_and_render_markdown
    html_content = markdown(
                   ^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\markdown\core.py", line 481, in markdown
    md = Markdown(**kwargs)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\markdown\core.py", line 126, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\markdown\core.py", line 179, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\markdown\core.py", line 225, in build_extension
    module = importlib.import_module(ext_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autolink'
2024-07-02 14:57:41,773 INFO: Blog startup [in C:\Users\15097\Desktop\FinalBlog\app.py:67]
2024-07-02 14:57:48,963 ERROR: Exception on /post/17 [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 201, in view_post
    sanitized_content = sanitize_and_render_markdown(post.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\utils.py", line 147, in sanitize_and_render_markdown
    html_content = markdown(
                   ^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\markdown\core.py", line 482, in markdown
    return md.convert(text)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\markdown\core.py", line 384, in convert
    output = pp.run(output)
             ^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\utils.py", line 26, in run
    start, end = link["index"], link["lastIndex"]
                 ~~~~^^^^^^^^^
TypeError: 'Match' object is not subscriptable
2024-07-02 14:58:11,873 INFO: Fetched 16 posts [in C:\Users\15097\Desktop\FinalBlog\app.py:101]
2024-07-02 14:58:23,916 INFO: Post created: urls [in C:\Users\15097\Desktop\FinalBlog\app.py:161]
2024-07-02 14:58:23,926 INFO: Fetched 17 posts [in C:\Users\15097\Desktop\FinalBlog\app.py:101]
