2024-07-11 18:57:47,990 INFO: Blog startup [in c:\Users\15097\Desktop\FinalBlog\tempCodeRunnerFile.py:112]
2024-07-11 18:57:49,359 INFO: Blog startup [in c:\Users\15097\Desktop\FinalBlog\tempCodeRunnerFile.py:112]
2024-07-11 19:01:09,322 INFO: Blog startup [in c:\Users\15097\Desktop\FinalBlog\tempCodeRunnerFile.py:112]
2024-07-11 19:01:24,076 INFO: Blog startup [in c:\Users\15097\Desktop\FinalBlog\tempCodeRunnerFile.py:112]
2024-07-11 19:05:45,444 INFO: Blog startup [in C:\Users\15097\Desktop\FinalBlog\app.py:112]
2024-07-11 19:05:47,687 ERROR: Exception on / [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 183, in home
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(
            ^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 22, in __get__
    return cls.query_class(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 275, in __init__
    self._set_entities(entities)
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 288, in _set_entities
    coercions.expect(
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 389, in expect
    insp._post_inspect
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2711, in _post_inspect
    self._check_configure()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2388, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4204, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4245, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2405, in _post_configure_properties
    prop.init()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 584, in init
    self.do_init()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1647, in do_init
    self._generate_backref()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2075, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'author' on relationship 'User.posts': property of that name exists on mapper 'Mapper[Post(post)]'
2024-07-11 19:12:11,413 INFO: Blog startup [in C:\Users\15097\Desktop\FinalBlog\app.py:112]
2024-07-11 19:12:14,303 ERROR: Exception on / [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_caching\__init__.py", line 426, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_caching\__init__.py", line 185, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 183, in home
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(
            ^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_sqlalchemy\model.py", line 22, in __get__
    return cls.query_class(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 275, in __init__
    self._set_entities(entities)
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 288, in _set_entities
    coercions.expect(
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 389, in expect
    insp._post_inspect
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2711, in _post_inspect
    self._check_configure()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2388, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4204, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4245, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2405, in _post_configure_properties
    prop.init()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 584, in init
    self.do_init()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1647, in do_init
    self._generate_backref()
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2075, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'author' on relationship 'User.posts': property of that name exists on mapper 'Mapper[Post(post)]'
2024-07-11 19:15:28,374 INFO: Blog startup [in C:\Users\15097\Desktop\FinalBlog\app.py:112]
2024-07-11 19:15:36,236 ERROR: Exception on /profile/Chris [GET] [in C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15097\Desktop\FinalBlog\app.py", line 434, in profile
    form.social_media.data = current_user.social_media
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'social_media'
